# Generated by Django 5.2.4 on 2025-10-27 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_task_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
