services:
  app:
    container_name: better-lyfe
    build:
      context: .
      dockerfile: ./dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./:/app
      - ./data/web/static:/data/web/static
      - ./data/web/media:/data/web/media
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - database
    networks:
      - app_network
  database:
    container_name: better-lyfe-database
    image: postgres:14-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env
    ports:
      - 5432:5432
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
